### ISSUE TITLE
tldExists(ipv4_1-lagg0-c026.1.lax004.ix.nflxvideo.net) returns False

### ISSUE THREAD

**Issue by guerrerocarlos** [oncletom/tld.js#75] opened 2016-03-22 03:34 UTC
Seems that if there is an underscore "_" in the domain, it returns False instead of True when checking the existence of the domain TLD

**Comment by ZLightning** [comment] 2016-05-06 04:09
This is a duplicate of #73

**Comment by oncletom** [comment] 2016-09-13 17:42
Yeah exactly. I will close it and encourage you to subscribe to #73 to follow the progress around that issue.

**Closed by oncletom** 2016-09-13 17:42 UTC
